---
title: Statistical Learning
---

```{r}
#| warning: false
library(dplyr)
library(ggplot2)
library(ISLR2)
```


The relationship between $Y$, the vector of values of the response variable, and $X$, the matrix of predictor variables, is written as:

$$
Y = f(X) + \epsilon
$$ 

Where $\epsilon$ is ideally a *random error term* independent from $X$ with a *mean of zero*. The qualifier *random* is important because it signals the errors need to be uncorrelated with $X$. Uncorrelated errors are desirable because otherwise, the model (i.e. relationship) would perform inconsistently across the values of $X$. The *mean of zero* is important because otherwise, the model would systematically inflate predictions if the mean was above zero, and systematically deflate predictions if the mean was below zero.

There are two main reasons to try estimate $f$:

1. prediction
2. inference

The book distinguishes reducible vs. irreducible error, with the former arising from the systematic component of the model and being reduceable by choosing a better modelling technique. The irreducible error is $\epsilon$ and it cannot be reduced (short of collecting more data to bring unexplained variation into explained variation)

If we wanted to be explicit when modelling for prediction, we could wrap the terms in a hat, to emphasize they are estimates of an estimand. We can also drop the error, assuming it to be zero. $\hat{Y}$ represents our estimates for the true value of $Y$. $\hat{f}$ represents our estimate for the relationship between the predictor variables. 

$$
\hat{Y} = \hat{f}(X)
$$

For predictions, $\hat{f}$ is often treated as a black box - we don't care how the variables in $X$ are modelled (linearly, non-linearly) or how they interact (additively, multiplicatively). That's different in inference, where understanding these relationships is the whole point. 

We are trying to estimate $f$ with our training data

$$
{(x_1, y_1), (x_2, y_2), ..., (x_n, y_n)}
$$

where: 

- $x_i = (x_{i1}, x_{i2}, x_{i3}, ..., x_{ip})^T$


Techniques to find $f$ are typically either parametric or non-parametric. Parametric techniques seem familiar to me. First, we make an assumption about the shape or functional form of $f$. Typically, this is that the function $f$ is linear: 

$$
f(X) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + ... + \beta_p X_p
$$

where:

- $\beta_0$ is the intercept
- $\beta_1$ is the slope of the relationship between predictors and response
- All $\beta$ values are known as the model parameters

One advantage of assuming a linear model is it's simpler - this is intuitive if you consider that all we're doing is fitting a straight line. Another way to look at it is we only need to model $p + 1$ parameters (slopes for every parameter plus the intercept, $\beta_0$). The downside to a parametric approach is the model may not closely fit the true, unknown form of $f$. It seems like there may be a suite of models called *flexible* models that can combat this concern (but see overfitting).

Once we've selected a model, we need to train it or fit it to the data. A common way to fit data to a line is ordinary least squares (OLS).

Another way of viewing the linear model equation above is to inject predictor variables into it:

$$
\texttt{income} \approx \beta_0 + \beta_1 \times \texttt{education} + \beta_2 \times \texttt{seniority}
$$

Non-parametric methods do not make assumptions about the relationships between the predictor and response variables, so in essence they're more flexible. However, this flexibility comes with a cost — the need for more observations. This feels intuitive since if we can assume the functional form of $f$, we're assuming we understand something about the relationship between $X$ and $Y$. In non-parametric methods, we don't assume a function form of $f$, which is like we're not assuming we understand anything, and we therefore need more data.

Note that non-parametric methods may be more sensitive to overfitting than parametric methods.

Restrictive (i.e. parametric models) shine in inference because they are more interprettable 

Statistical learning problems typically fall into one of two other categories:

1. Supervised
2. Unsupervised 

Note that there is also semi-supervised learning which has some hallmarks of both supervised and unsupervised learning

Statstical learning problems with a quantitative response are typically thought of as regression problems. Conversely, those with a qualitative response are typically thought of as classification problems. However, the dividing line isn't always clean. Consider logistic regression which produces quantitative probabilities for qualitative outcomes and yet is typically thought of as a tool for classification. 

Whether the predictors are quantitative or qualitative is typically less important. I *think* this is because in statistical learning, qualitative predictors are actually treated as quantitative under the hood. 

There is no 'best' method for statistical learning - each has its strengths and may perform well on a particular dataset. Since we can't just rely on a 'best' model, we need to have ways to measure the accuracy or 'goodness' of our model. 

A common metric is mean squared error (MSE):

$$
MSE = \dfrac{1}{n}\sum_{i=1}^{n}(y_i - \hat{f}(x_i))^2
$$

MSE is small if the residuals are small (i.e. the fitted predictions are close to the observed values). Note that MSE is calculated on training data and could more accurately be called the *training MSE*. In reality, we don't report on the *training MSE* and are more interested in the test *MSE*, at least for prediction use-cases. 

The flexibility of a model is linked to its degrees of freedom. 

Overfitting can be thought of as low training MSE and high test MSE. It is when the function $\hat{f}$ learns idiosyncratic patterns unique to the training data and then tries to apply that knowledge in predictions on test data, the catch is, those idiosyncratic patterns (essentially random variation) aren't identical in the test data, so test MSE tanks. 

With the data we are handed to fit the model, we typically use a method called cross-validation to estimate the test MSE using the training data. 

The expected test MSE for a given value $x_0$ can be decomposed into three fundamental quantities:

1. the variance of $\hat{f}(x_0)$

2. the squared bias of $\hat{f}(x_0)$

3. the variance of the error terms $\epsilon$

$$

E(y_0 - \hat{f}(x_0))^2 = \text{Var}(\hat{f}(x_0)) + [\text{Bias}(\hat{f}(x_0))] + \text{Var}(\epsilon)

$$

where:

- $E(y_0 - \hat{f}(x_0))^2$ represents the expected test MSE at $x_0$

Since the first two terms, $\text{Var}(\hat{f}(x_0))$ and $[\text{Bias}(\hat{f}(x_0))]$, come from $\hat{f}$, we can imagine trying to drive both the variance and the bias of the model down. Both of these terms are positive and thus the test MSE is always going to be greater than the irreducible error from $\text{Var}\epsilon$. 

In other words, the first two terms are properties of the model that I can control. The last term is a property of reality that I can't control. 

In this context, variance essentially measures how much the function $\hat{f}$ changes with a different training data set. More flexible models like curved splines typically have higher variance than less flexible models like linear regression. 

As we apply more flexible models, bias tends to decrease more quickly than variance increases. At some point, bias stops decreasing appreciably while the variance continues to increase. This suggests there is an optimum that we can strive to reach. This is the *bias-variance trade-off*. 

